name: Deploy to Fasthosts

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Deploy website via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: sftp.weedcontrolkent.co.uk
        username: csh3368367
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        local_path: './*'
        remote_path: 'htdocs/'
        sftp_only: true
